from django.urls import path

from . import views

urlpatterns = [
    path('',
         views.IndexList.as_view(),
         name='posts'),
    path('group/',
         views.GroupsList.as_view(),
         name='groups'),
    path('group/<slug:slug>/',
         views.GroupPosts.as_view(),
         name='group-posts'),
    path('authors/',
         views.ProfilesList.as_view(),
         name='authors'),
    path('new/',
         views.PostCreate.as_view(),
         name='new-post'),
    path('follow/',
         views.FollowList.as_view(),
         name='follow_index'),
    path('<str:username>/',
         views.ProfilePosts.as_view(),
         name='profile'),
    path("<str:username>/follow/",
         views.ProfileFollow.as_view(),
         name="profile-follow"),
    path("<str:username>/unfollow/",
         views.ProfileUnFollow.as_view(),
         name="profile-unfollow"),
    path('<str:username>/<int:post_id>/',
         views.PostView.as_view(),
         name='post'),
    path('<str:username>/<int:post_id>/edit/',
         views.PostEdit.as_view(),
         name='post-edit'),
    path('<str:username>/<int:post_id>/comment/',
         views.PostAddComment.as_view(),
         name='add-comment'),
]
