# Generated by Django 3.1.2 on 2020-10-05 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_maker', '0003_sitemap_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(help_text='Your site url', unique=True),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_site', to='ads_maker.site'),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='url',
            field=models.URLField(help_text='Sitemaps URL', unique=True),
        ),
    ]
