# Generated by Django 3.1.2 on 2020-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_maker', '0005_auto_20201005_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='is_sm_index',
            field=models.BooleanField(null=True),
        ),
    ]
